# Site settings
title: Mustafa Samed Eskin
description: 'Portfolio Page'
url: 'https://eskinmi.github.io/'
baseurl: ''
profilepic: '/images/eskinmi.jpg'
bkimage: '/images/background.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Mustafa Samed Eskin'
  email: mustafasamedeskin@gmail.com
  twitter_username: mustafaeskinn
  facebook_username: MustafaEskinn
  github_username:  eskinmi
  linkedin_username:  mustafasamedeskin
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
